name: Lint
on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        server-versions: ['3_2_1-1']

    name: php-cs check php${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        run: composer install

      - name: Run coding standards check
        run: composer run phpcs
