name: PHPUnit

on:
  pull_request:
  push:
    branches: [ main ]

env:
  OJS_WEB_BASEDIR: /app/ojs
  OJS_LOGIN_URL: http://localhost/ojs/index.php/csp/login/signIn

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
        databases: ['mysql']
        server-versions: ['3_2_1-1']
    name: php${{ matrix.php-versions }}-${{ matrix.databases }}-${{ matrix.server-versions }}
    services:
      mysql:
        image: mariadb
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout OJS
        uses: actions/checkout@v2
        with:
          repository: pkp/ojs
          path: ojs/
          ref: ${{ matrix.server-versions }}

      - name: Checkout OJS submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1 --git-dir=ojs

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gettext, intl, mysql, pdo_mysql

      - name: Install OJS
        run: |
          php tests/setupOjs.php

      - name: Install Composer dependencies
        run: |
          composer install
          composer --working-dir=ojs/lib/pkp install

      - name: PHPUnit
        run: composer unit
